[deploy]
bucket = 'cfn-artifacts-flowerpot'
region = 'ca-central-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:806329234304:certificate/50147d36-9d63-4b8f-9ea0-c51fa9e35cbe'
WwwBucketName = 'www.flowerpot76.com'
RootBucketName = 'flowerpot76.com'